name: AWS Github Action Github IAM user
run-name: Github Action with IAM user aws-access-key-id
on:
  push:
    branches:
      - 'git-actions1'
jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: List s3 files
        run: |
          aws s3api list-buckets
      - name: List all iam roles
        run: |
          aws iam list-roles